### ISSUE TITLE
Python 3.13 - ModuleNotFoundError: No module named 'pipes'

### ISSUE THREAD

**Issue by diodakus** [gchamon/sysrsync#45]
Python 3.13 during installation sysrsync-0.1.2 reports error:
```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<31 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('/tmp/pip-download-vi5h_xid/sysrsync_2e5c53d45081406c80890feee1a1083f/setup.py',), "<pip-setuptools-caller>", "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-download-vi5h_xid/sysrsync_2e5c53d45081406c80890feee1a1083f/setup.py", line 3, in <module>
          from sysrsync import __version__
        File "/tmp/pip-download-vi5h_xid/sysrsync_2e5c53d45081406c80890feee1a1083f/sysrsync/__init__.py", line 3, in <module>
          from .command_maker import *
        File "/tmp/pip-download-vi5h_xid/sysrsync_2e5c53d45081406c80890feee1a1083f/sysrsync/command_maker.py", line 6, in <module>
          from .helpers.files import is_path_to_file
        File "/tmp/pip-download-vi5h_xid/sysrsync_2e5c53d45081406c80890feee1a1083f/sysrsync/helpers/files.py", line 2, in <module>
          import pipes
      ModuleNotFoundError: No module named 'pipes'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by gchamon** [comment]
Why are you using 0.1.2? Latest version is 1.1.1

**Comment by gchamon** [comment]
Unable to reproduce this issue with the latest version of sysrsync:

```bash
docker run --rm python:3.13 pip install sysrsync
```
